POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFobTNyIiwiaWQiOiI2MGUxMjFiNzhlN2I5NGI3Y2M0NmFkMDYiLCJpYXQiOjE2MjUzNjg3OTIsImV4cCI6MTYyNTM3MjM5Mn0.fAzYltZnj-VZYx6SvTxJtLPG4HEAr_a8JhwcOOmbt5M

{
  "title": "React",
  "author": "Anonymous",
  "url": "https://react.com/",
  "likes": 6
}

###
GET http://localhost:3003/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFobWVyIiwiaWQiOiI2MGNkOTFlZmNlNzg5ODE0YTZmYmM5MDgiLCJpYXQiOjE2MjQxNTc5NjYsImV4cCI6MTYyNDE2MTU2Nn0.ehHZAtddnE-l9DfXpCVGo1Puxr5aeCSUnAoWAEz-PNw

###
DELETE http://localhost:3003/api/blogs/60ceafd7b119574796ffe6c0
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFobWVyIiwiaWQiOiI2MGNkOTFlZmNlNzg5ODE0YTZmYmM5MDgiLCJpYXQiOjE2MjQxNTc5NjYsImV4cCI6MTYyNDE2MTU2Nn0.ehHZAtddnE-l9DfXpCVGo1Puxr5aeCSUnAoWAEz-PNw

###
PUT http://localhost:3003/api/blogs/60cadb7b1c49c04b0c4566be
Content-Type: application/json

{
    "likes": 9
}

###
POST http://localhost:3003/api/blogs/60ceab5e9cf2d4449a87cb52/comments
Content-Type: application/json

{
  "comment": "testiing blog"
}