POST http://localhost:3002/api/persons
Content-Type: application/json

{
    "name": "Ahme",
    "number": "0900-ffe78601"
}

###
GET http://localhost:3002/api/persons/60c96947d9e70bd575ca6d60

###
DELETE http://localhost:3002/api/persons/60c96947d9e70bd575ca6d60

###
GET http://localhost:3002/api/persons
